#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP -d 1 2 
bspc monitor HDMI-A-0 -d 3 4 5
bspc config border_width        0
bspc config window_gap          2

bspc config focus_follows_pointer true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true


#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^3' 
bspc rule -a code-oss desktop='^4' state=floating rectangle=1920x1080+0+0
bspc rule -a TelegramDesktop desktop='^5' state=floating rectangle=1920x1080+0+0 
#bspc rule -a Alacritty desktop='^2' state=floating 


#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#feh --bg-fill --randomize ~/.wal/*

# Autstart
code-oss
telegram-desktop
Navigator
